# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      # Custom H2 Console URL
      path: /h2

logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log


