DROP TABLE IF EXISTS TBL_USUARIO;

DROP TABLE IF EXISTS TBL_PRODUCTO;
DROP TABLE IF EXISTS TBL_VENTA;
DROP TABLE IF EXISTS TBL_DETALLE_VENTA;
DROP TABLE IF EXISTS TBL_CLIENTE;

CREATE TABLE TBL_CLIENTE (
  idCliente INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL,
  apellido VARCHAR(250) NOT NULL,
  dni VARCHAR(8) DEFAULT NULL,
  telefono VARCHAR(13) DEFAULT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE TBL_PRODUCTO (
  idProducto INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL,
  precio DECIMAL NOT NULL
);

CREATE TABLE TBL_VENTA (
  idVenta INT AUTO_INCREMENT  PRIMARY KEY,
  idCliente INT NOT NULL,
  fecha DATE NULL,
  FOREIGN KEY (idCliente) REFERENCES TBL_CLIENTE(idCliente)
);

CREATE TABLE TBL_DETALLE_VENTA (
  idDetalleVenta INT AUTO_INCREMENT  PRIMARY KEY,
  idProducto INT NOT NULL,
  idVenta INT NOT NULL,
  FOREIGN KEY (idProducto) REFERENCES TBL_PRODUCTO(idProducto),
  FOREIGN KEY (idVenta) REFERENCES TBL_VENTA(idVenta)
);

